config/routes.rb
Pms::Application.routes.draw do
  devise_for :users

   resources :users do
			member do
				get 'user_task'
        get 'all_tasks'
     	end
		end
    resources :projects do
     resources :login_details
   	 resources :project_repositories do
   	  member do
   	    get 'download_doc'  
   	  end
   	 end
      resources :project_users
	     resources :project_modules  do
        resources :tasks do
			    member do
					  get 'task_update'
            get 'task_under'
            get 'task_deploy'
					end
				end
      end
	 end
	get '/task/:user_id/:task_id/:status/status_update' => "users#status_update" , :as => "status_update"
 

    root :to => 'home#index'

end

app/models/login_detail.rb
class LoginDetail < ActiveRecord::Base
end

app/controllers/login_details_controller.rb
class LoginDetailsController < ApplicationController

  def index
    @project = Project.find(params[:project_id])
    @login_details = @project.login_details
  end
  
  def new
    @project = Project.find(params[:project_id])
    @login_detail = @project.login_details.new
  end
  
  def create
    @project = Project.find(params[:project_id])
    @login_detail = @project.login_details.new(login_params)
    if @login_detail.save
      redirect_to project_login_details_path(@project)
    else
      render :new
    end
  end
  
  def edit
    @project = Project.find(params[:project_id])
    @login_detail = @project.login_details.find(params[:id])
  end
  
  def show
  end
  
  def update
    @project = Project.find(params[:project_id])
    @login_detail = @project.login_details.new(login_params)
    if @login_detail.update_attributes(login_params)
      redirect_to project_login_details_path(@project)
    else
      render :new
    end
  end
  
  def destroy
  end
  
  
  private
  
  def login_params
    params.require(:login_detail).permit(:user_name, :password, :git_url, :description) 
  end
end

app/helpers/login_details_helper.rb
module LoginDetailsHelper
end

app/views/login_details/_form.html.erb
<%= form_for [@project, @login_detail] do |f| %>
  <p>
    <%= f.label :user_name %>
    <%= f.text_field :user_name %>
  </p>
  <p>
    <%= f.label :password %>
    <%= f.text_field :password %>
  </p>
  <p>
    <%= f.label :git_url %>
    <%= f.text_field :git_url %>
  </p>
  <% if @project.new_record? %>
  <p>
    <%= f.label :description %>
    <%= f.text_area :description, rows: 8, cols: 5 %>
  </p>
  <% end %>
  <p>
    <%= f.submit :Submit, class: "btn" %>
    <%= link_to "Cancel", project_login_details_path(@project), class: "btn" %>
  </p>
<% end %>

app/views/login_details/edit.html.erb
<%= render 'form' %>

app/views/login_details/index.html.erb
<table class = table "table-bordered"   cellspacing="3" cellpadding="4" >
<tr>
  <th>PROJECT NAME</th>
  <th><%= @project.project_name %></th>
</tr>
 <tr class="rowH" height="30">	
		<th>User Name</th>
 		<th>Password</th>	
		<th>Git Url</th>
		<th>Description</th>
		<th>Actions</th>
 </tr>
 <tr>
	<%if @login_details.present? %>
	  <% @login_details.each do |ld| %>
	    <tr>
	      <td><%= ld.user_name %></td>		
        <td><%= ld.password %> </td>
        <td><%= ld.git_url %></td>
        <td><%= ld.description %></td>
		    <td>
		      <li class="dropdown" style="list-style:none;" >
		       <%= link_to "Click Here" , "#",  :'data-toggle' => "dropdown", class: "dropdown-toggle"  %>
	         <ul class="dropdown-menu" style="list-style:none;">
            <li>
              <%= link_to 'Edit', edit_project_login_detail_path(@project, ld)%>
              <%= link_to 'Delete', project_login_detail_path(@project, ld), :method=> :delete %>
        	    <%= link_to 'Show', project_login_detail_path(@project, ld) %>
      	    </li>
        	 </ul>
      	 </li>
      </td>
  	</tr>
		<% end %>
		<% else %>
		  <td>
			  No login details available
		  </td>
	<% end %>
	</tr>
</table>
<div class="pull-right">
  <%= link_to "Add Login Details", new_project_login_detail_path(@project), class: "btn" %></td>
</div>

app/views/login_details/new.html.erb
<h2>New Login Details</h2>
<div style="clear:both;"></div>
<%= render 'form' %>