config/routes.rb
Pms::Application.routes.draw do
  devise_for :users

   resources :users do
			member do
				get 'user_task'
        get 'all_tasks'
     	end
		end
    resources :projects do
     resources :login_details
   	 resources :project_repositories do
   	  member do
   	    get 'download_doc'  
   	  end
   	 end
      resources :project_users
	     resources :project_modules  do
        resources :tasks do
			    member do
					  get 'task_update'
            get 'task_under'
            get 'task_deploy'
					end
				end
      end
	 end
	get '/task/:user_id/:task_id/:status/status_update' => "users#status_update" , :as => "status_update"
 

    root :to => 'home#index'

end

app/models/task.rb
class Task < ActiveRecord::Base
  #attr_accessible :est_end_date, :project_id, :est_start_date, :act_start_date,:act_end_date,:user,:task_description
  #attr_accessible :task,:user_id,:project_module_id,:status
  validates :est_start_date, :est_end_date, :task, :presence => true
  validates :task, uniqueness: true
  validate  :date_validation
  belongs_to :project_module
  belongs_to :user
 
  def date_validation
    if (self.est_start_date.present? && self.est_end_date.present?) && (self.est_start_date > self.est_end_date)
	  	errors[:date] << "Est. Start date must be less than Est. end date"
	  end
  end


end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
 load_and_authorize_resource :except=>[:task_update,:task_under,:task_deploy]
 before_action :check_manager
 before_action do
    Time.zone =  "Asia/Kolkata"
    @project = Project.find(params[:project_id])
    @users = @project.project_users
 end
 before_action :check_module_date, only: [:create, :update]

	def new
		@project = Project.find(params[:project_id])
		@project_module = ProjectModule.find(params[:project_module_id])
		@users = @project.project_users
		if !@project_module.act_end_date.present?
		  @task = @project_module.tasks.new
		else
		  redirect_to project_project_module_tasks_path(@project,@project_module), notice: "Sorry!! Module is already completed."
		end
	end

	def index
		@project = Project.find(params[:project_id])
		@project_module = ProjectModule.find(params[:project_module_id])
		@tasks = @project_module.tasks
	end
	
	def create	
	  @project = Project.find(params[:project_id])
		@project_module = ProjectModule.find(params[:project_module_id])
		@task  =@project_module.tasks.new(task_params)
		if @task.save
			redirect_to project_project_module_tasks_path(@project,@project_module), :notice => "Successfully submit Task's details"
		else
			render :new 
		end		
  end

  def edit
   @project = Project.find(params[:project_id])
   @project_module = ProjectModule.find(params[:project_module_id])
   @task  = Task.find(params[:id])
  end

  def show
   @project = Project.find(params[:project_id])
   @project_module = ProjectModule.find(params[:project_module_id])
   @task  =  @project_module.tasks.find(params[:id])
  end

  def update
   @project = Project.find(params[:project_id])
   @project_module = ProjectModule.find(params[:project_module_id])
   @task= @project_module.tasks.find(params[:id])
    if @task.update_attributes(task_params)
     redirect_to project_project_module_tasks_path(@project, @project_module), :notice => "Updated Successfully"
     else
      render :edit , :notice => "sorry..something is wrong"
    end
  end

  def destroy
   @project = Project.find(params[:project_id])
   @project_module = ProjectModule.find(params[:project_module_id])
   task = Task.find(params[:id])  
   task.destroy
    redirect_to project_project_module_tasks_path(@project,@project_module), :notice => "Successfully deleted"
  end
	
	def task_update
    #ProjectUser.update_all({start_date: Time.now.in_time_zone("Asia/Kolkata")},["project_id = ?", @project.id.to_s])
    task = Task.find(params[:id])
    task.act_start_date = Time.now.in_time_zone("Asia/Kolkata")
    task.status = params[:status]	
    if task.save
      @project_module = ProjectModule.find(params[:project_module_id])
      if !@project_module.act_start_date.present?
        @project_module.act_start_date = Time.now.in_time_zone("Asia/Kolkata")
        if @project_module.save
          @project = Project.find(params[:project_id])
          if !@project.act_start_date.present?
            @project.act_start_date = Time.now.in_time_zone("Asia/Kolkata")
            @project.save
          end
        end
      end
      if task.status == 3
        s = @project_module.tasks.where.not("status = ?", 3)
        if s.size==0
         @project_module.act_end_date=	Time.now.in_time_zone("Asia/Kolkata")
         @project_module.project.act_end_date= Time.now.in_time_zone("Asia/Kolkata")
         @project_module.save
         @project_module.project.save
         redirect_to project_project_module_tasks_path(@project, @project_module), :notice => "Module completed"
         return
        end
      end
	    redirect_to project_project_module_tasks_path(@project, @project_module), notice: "Task Updated"
    else
	    redirect_to project_project_module_tasks_path(@project, @project_module), notice: "oops...task not updated"
    end 
	end
   
  

private
  def check_manager
	 @project = Project.find(params[:project_id]) 
	 redirect_to projects_path  if @project.user != current_user && !current_user.isAdmin
	end

  def task_params
   params.require(:task).permit(:est_end_date, :project_id, :est_start_date, :act_start_date,:act_end_date,:user,:task_description,
    :task,:user_id,:project_module_id,:status)
  end
  
  def check_module_date
    @project = Project.find(params[:project_id])
    if !@project.act_start_date.present?
      @project.act_start_date  = Time.now.in_time_zone("Asia/Kolkata")
    end
    @project_module = ProjectModule.find(params[:project_module_id])
 		if @project_module.present?
      if !@project_module.act_start_date.present?
        @project_module.act_start_date  = Time.now.in_time_zone("Asia/Kolkata")
      end
      if (params[:task][:est_start_date].present? && (params[:task][:est_start_date]).to_date < (@project_module.est_start_date))
  		  flash[:notice] = "Task Rejected as task's Estimated Start date is less than Module's Estimated Start date"
  			redirect_to new_project_project_module_task_path(@project, @project_module)
 			elsif (params[:task][:est_end_date].present? && (params[:task][:est_end_date]).to_date > (@project_module.est_end_date)) 
 				flash[:notice] = "Task Rejected as Task's Estimated End date is greater than Module's Estimated End date"
 				redirect_to new_project_project_module_task_path(@project, @project_module)
      end
    end
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
	def current_time
	 	Time.now.in_time_zone("Asia/Kolkata")
	end
end

app/views/tasks/_form.html.erb
 <script>
 $(function() {
   $("#datepicker_est_start_date").datetimepicker({format: 'dd/MM/yyyy hh:mm:ss'})
   $("#datepicker_est_end_date").datetimepicker({format: 'dd/MM/yyyy hh:mm:ss'});
 });
 </script>
<div>
	<%= form_for [@project,@project_module,@task] do |f| %>
    <% if @task.errors.any? %>
      <div class="error_messages">
        <h2>Form is invalid</h2>
        <div style="clear:both;"></div>
      	<ul>
	        <% for message in @task.errors.full_messages %>
	          <li><%= message %></li>
	        <% end %>
	      </ul>
      </div>
  <% end %>
	<div>
		<%= f.label "User" %>
		<%= f.select :user_id, @users.map {|u| [u.user.email,u.user.id]} if @users.present?%>
	</div>
  <div>
		<%= f.label "Task" %>
		<%= f.text_field :task %>
	</div>
  <div class="input-append date" id="datepicker_est_start_date"  data-date="<%=Date.today.strftime('%d-%m-%Y')%>">
	  <%= f.label :est_start_datetime %>
	  <%= f.text_field :est_start_date, readonly: true %>
		<span class="add-on"><i class="icon-th"></i></span>
	</div>
	<div class="input-append date" id="datepicker_est_end_date" data-date="<%=Date.today.strftime('%d-%m-%Y')%>" >
		<%= f.label :est_end_datetime %>
		<%= f.text_field :est_end_date, readonly: true %>
 	  <span class="add-on"><i class="icon-th"></i></span>
	</div><br>    
	<div>
		<%= f.submit "Submit" , class: "btn" %>
		<%= link_to :Cancel, project_project_module_tasks_path(@project.id, @project_module.id) , class: "btn" %>
	</div>
<% end %>
</div>

app/views/tasks/edit.html.erb
<h2>Modify Task </h2>
<div style="clear:both;"></div>
<%= render 'form' %>

app/views/tasks/index.html.erb
<table class = table "table-bordered"   cellspacing="0" cellpadding="0" border="0" style="overflow-x:auto;">
 <tr>
   <th>Project Name</th>
   <th colspan=10><%= @project.project_name %></th>
 </tr>
 <tr>
   <th>Module Name</th>
   <th colspan=10><%= @project_module.project_module_name %></th>
 </tr>
 
<tr class="rowH" height="30">
  <th>User</th>
  <th>Task</th>
  <th>Est. start datetime</th>
  <th>Est. end datetime</th>
  <th>Actions</th>
  <th>Task Status</th>
</tr>
<tr>
<% @tasks.each do |t| %>
   <% if  (t.status == 0 or t.status == 1) %> 
      <tr style="background:red;">
   <% elsif (t.status == 0) %>
      <tr style="background:yellow;">
    <% else %>
	     <tr>
    <% end %>
         <td><%= t.user.try(:email) %></td>
         <td><%= t.task %></td>
         <td><%= t.est_start_date.strftime("%d-%m-%Y %H:%M:%S") %></td>
         <td><%= t.est_end_date.strftime("%d-%m-%Y %H:%M:%S") %></td>
          <td>
	           <li class="dropdown" style="list-style:none;">
              <a href="#" class = "dropdown-toggle" data-toggle = "dropdown">Click Here</a>
			            <ul class="dropdown-menu" style="list-style:none;">
                    <li><%= link_to 'Edit', edit_project_project_module_task_path(@project,@project_module, t) %></li>
                    <li><%= link_to 'Delete', project_project_module_task_path(@project,@project_module, t), :method=> :delete %></li>
                    <li><%= link_to 'Show', project_project_module_task_path(@project,@project_module, t)%></li>
                    <% if t.status == 0 %>
                      <li><%= link_to 'Start', task_update_project_project_module_task_path(@project.id, @project_module.id, t.id, status: 1), :class => "btn btn-small active" %></li>
                    <% elsif t.status == 1 %>
                      <li><%= link_to TASK_STATUS[2], task_update_project_project_module_task_path(@project.id, @project_module.id, t.id, status: 2),:class=> "btn btn-small active"%></li>
                    <% elsif t.status == 2 %> 
                      </li><%= link_to TASK_STATUS[3], task_update_project_project_module_task_path(@project.id, @project_module.id, t.id, status: 3), :class => "btn btn-small active"%>
                     <% end %>
                  </ul>
              </li>
            </td>
            <td><%= TASK_STATUS[t.status] %></td>
      </tr>
<% end %>
</table>
<div class="pull-right">
   <%=link_to "ADD NEW TASK" , new_project_project_module_task_path(@project, @project_module), class: "btn" %>
 </div>

app/views/tasks/new.html.erb
<h2>New Task </h2>
<div style="clear:both;"></div>
<%= render 'form' %>

app/views/tasks/show.html.erb
<table class = table "table-bordered"   cellspacing="0" cellpadding="0" >
	<tr>
		<td><b>User</b></td>
		<td><%=@task.user.try(:email)%></td>
	</tr>
  <tr>
		<td><b>Task</b></td>
		<td><%=@task.task%></td>
	</tr>
   <tr>
		<td><b>Est. Start datetime</b></td>
		<td><%=@task.est_start_date.strftime("%d-%m-%Y %H:%M:%S")%></td>
	</tr>
  <tr>
		<td><b>Est. End datetime</b></td>
		<td><%=@task.est_end_date.strftime("%d-%m-%Y %H:%M:%S")%></td>
	</tr>
 </table>
               