config/routes.rb
Pms::Application.routes.draw do
  devise_for :users

   resources :users do
			member do
				get 'user_task'
        get 'all_tasks'
     	end
		end
    resources :projects do
     resources :login_details
   	 resources :project_repositories do
   	  member do
   	    get 'download_doc'  
   	  end
   	 end
      resources :project_users
	     resources :project_modules  do
        resources :tasks do
			    member do
					  get 'task_update'
            get 'task_under'
            get 'task_deploy'
					end
				end
      end
	 end
	get '/task/:user_id/:task_id/:status/status_update' => "users#status_update" , :as => "status_update"
 

    root :to => 'home#index'

end

app/models/project_repository.rb
class ProjectRepository < ActiveRecord::Base
  #attr_accessible  :project_id
  #attr_accessible :name, :document, :remote_document_url
   validates :title,  :presence => true
   belongs_to :project
   mount_uploader :document, DocumentUploader
end

app/controllers/project_repositories_controller.rb
class ProjectRepositoriesController < ApplicationController
  before_filter :check_manager
	def new
  	@project = Project.find(params[:project_id])
  	@project_repository = @project.project_repositories.new
  end

  def create
  	@project = Project.find(params[:project_id])
  	@project_repository  = @project.project_repositories.new(project_repository_params)
		if @project_repository.save
 			redirect_to project_project_repositories_path(@project), :notice => "Successfully submit project repository details"
		else
 			render :new 
    end
  end

  def index
  	@project = Project.find(params[:project_id])
   	@project_repositories = @project.project_repositories
  end

  def show
  	@project = Project.find(params[:project_id])
  	@project_repository  =  @project.project_repositories.find(params[:id])
 	end
 	
 	def edit
    @project = Project.find(params[:project_id])
    @project_repository  =  @project.project_repositories.find(params[:id])
  end
 
  def update
    @project = Project.find(params[:project_id])
    @project_repository = @project.project_repositories.find(params[:id])
    if @project_repository.update_attributes(project_repository_params)
     redirect_to project_project_repositories_path(@project), :notice => "Updated Successfully"
    else
      render :edit , :notice => "sorry..something is wrong"
    end
  end

  def destroy
  	@project = Project.find(params[:project_id])
  	project_repository = @project.project_repositories.find(params[:id])  
  	project_repository.destroy
		redirect_to project_project_repositories_path(@project), :notice => "Successfully deleted"
 	end

 	
  def download_doc
    @project = Project.find(params[:project_id])
    @project_repository = @project.project_repositories.find(params[:id])
    send_file @project_repository.document.path, :filename => "project_doc_#{@project_repository.id}",  :disposition => 'attachment', :type => 'application/all', x_sendfile: true 
    return
    
  end

   private
    def check_manager
		 @project = Project.find(params[:project_id]) 
		 redirect_to projects_path  if @project.user != current_user && !current_user.isAdmin
		end
  	def project_repository_params
	  	params.require(:project_repository).permit(:project_id, :title, :document, :document_url)
    end
end

app/helpers/project_repositories_helper.rb
module ProjectRepositoriesHelper
end

app/views/project_repositories/_form.html.erb
<%= form_for([@project, @project_repository])  do |f| %>

  <% if @project_repository.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
       <div style="clear:both;"></div>
       <ul>
         <% for message in @project_repository.errors.full_messages %>
           <li><%= message %></li>
         <% end %>
      </ul>
    </div>
    <% end %>
  <div>
    <p>
      <%=f.label :title %>
      <%=f.text_field :title %>
    </p>
    <p>
      <%= f.file_field :document %>
    </p>
    <p>
       <%= f.label :document_url, " Document URL" %>
       <%= f.text_field :document_url %>
    </p>
    <p>
       <%= f.submit "Submit" , class: "btn" %>
       <%= link_to "Cancel" , project_project_repositories_path(@project), class: "btn" %>
    </p>
  </div>
<% end %>

app/views/project_repositories/edit.html.erb
<%= render 'form' %>

app/views/project_repositories/index.html.erb
<table class = table "table-bordered"   cellspacing="3" cellpadding="4" >
<tr>
  <th>PROJECT NAME</th>
  <th><%= @project.project_name %></th>
</tr>
 <tr class="rowH" height="30">	
		<th>Document Title</th>
 		<th>Attachment</th>	
		<th>Actions</th>
 </tr>
 <tr>
	<%if @project_repositories.present? %>
	  <% @project_repositories.each do |pr| %>
	    <tr>
	      <td><%= pr.title %></td>		
        <td><%= link_to File.basename(pr.document.url) , download_doc_project_project_repository_path(@project, pr) %> </td>
		    <td>
		      <li class="dropdown" style="list-style:none;" >
		       <%= link_to "Click Here" , "#",  :'data-toggle' => "dropdown", class: "dropdown-toggle"  %>
	         <ul class="dropdown-menu" style="list-style:none;">
            <li>
              <%= link_to 'Edit', edit_project_project_repository_path(@project, pr)%>
              <%= link_to 'Delete', project_project_repository_path(@project, pr), :method=> :delete %>
        	    <%= link_to 'Show', pr.document_url, :target=>"blank" %>
        	    <%= link_to "Download" , download_doc_project_project_repository_path(@project, pr) %> 
      	    </li>
        	 </ul>
      	 </li>
      </td>
  	</tr>
		<% end %>
		<% else %>
		  <td>
			  No repository available
		  </td>
	<% end %>
	</tr>
</table>
<div class="pull-right">
  <%= link_to "Add Document", new_project_project_repository_path(@project), class: "btn" %></td>
</div>

app/views/project_repositories/new.html.erb
<%= render 'form' %>

app/views/project_repositories/show.html.erb
<h1>Project Repository Information</h1>
<table width="800">
	
	

	        <td rowspan="3"><%= image_tag @project_repository.document_url(:thumb).to_s %></td>
	
	<tr>
		<td><b>Name</b></td><td>
		<td><%=@project_repository.name%></td>
	</tr>
        <tr>
		<td><b>Document</b></td><td>
		<td><%=@project_repository.document%></td>
	</tr>
       	
</table>
</center>

  