config/routes.rb
Pms::Application.routes.draw do
  devise_for :users

   resources :users do
			member do
				get 'user_task'
        get 'all_tasks'
     	end
		end
    resources :projects do
     resources :login_details
   	 resources :project_repositories do
   	  member do
   	    get 'download_doc'  
   	  end
   	 end
      resources :project_users
	     resources :project_modules  do
        resources :tasks do
			    member do
					  get 'task_update'
            get 'task_under'
            get 'task_deploy'
					end
				end
      end
	 end
	get '/task/:user_id/:task_id/:status/status_update' => "users#status_update" , :as => "status_update"
 

    root :to => 'home#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
     #attr_accessible  :description,:project_name,  :Est_start_date,:Est_end_date,:Act_start_date,:Act_end_date,:Additional_details,:user_id,:manager
   validates  :est_start_date,:est_end_date,:project_name, :presence => true
   belongs_to :user
   has_many :project_users, :dependent => :destroy
   has_many :project_repositories
   has_many :project_modules, :dependent => :destroy
   has_many :login_details, :dependent => :destroy
   validate :date_validation

  def date_validation
	  if  (self.est_start_date.present? && self.est_end_date.present?) && (self.est_start_date > self.est_end_date)
		  errors[:date] << "Start date must be less than end date"
	  end
  end


end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
 #load_and_authorize_resource 
 before_action :check_project_alloted, :only=>[:create, :update]
 before_action do
  @users = User.select("id, email").where(isManager: true)
 end
  def new
 	  @project  = Project.new
  end

 def create
  @project  = Project.new(project_params)
    if @project.save
	    redirect_to projects_path, :notice => "Successfully submit Project details"
    else
      render :new
    end
	end

  def index
  	@projects = Project.all
  end

  def show
  	@project  = Project.find(params[:id])
  end

  def update
  	@project = Project.find(params[:id])
    	if  @project.update_attributes(project_params)
      	redirect_to projects_path, :notice => "Updated Successfully"
       else
      	 render :edit , :notice => "sorry..something is wrong"
      end
  end

  def destroy
  	project = Project.find(params[:id])  
    project.destroy
    redirect_to projects_path
  end

  def edit
  	@project = Project.find(params[:id])
  end

  private
  	def project_params
     	params.require(:project).permit(:description,:project_name,:est_start_date,:est_end_date,:act_start_date,:act_end_date,
			:additional_details, :user_id, :manager)
    end
    
    def check_project_alloted
      user_project = Project.where(user_id: params[:project][:user_id]).first
  	  if user_project.present?
    	  project = Project.where("date(est_start_date) >=? and date(est_end_date) <=? and user_id=?", params[:project][:est_start_date].to_date,       user_project.est_end_date.to_date, params[:project][:user_id])
    	  redirect_to projects_path , notice: "Project Rejected: can't assign new project on same alotted dates" if project.present?
      end
    end
end 

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
 <script>
 $(function() {
 $("#datepicker_est_start_date").datetimepicker({format: 'dd/MM/yyyy hh:mm:ss'})
 $("#datepicker_est_end_date").datetimepicker({format: 'dd/MM/yyyy hh:mm:ss'});
 });
 </script>


	<%= form_for @project  do |f| %>
	  <% if @project.errors.any? %>
	  <div class="error_messages">
      <h2>Form is invalid</h2>
      <div style="clear:both;"></div>
      <ul>
        <% for message in @project.errors.full_messages %>
         <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <%end%>
     
	    <div>
		    <%=f.label :Project_Name %>
		    <%=f.text_field :project_name %>
	    </div>
      <div>
				<%=f.label :Manager %>
				<%=f.select :user_id, @users.map {|u| [u.email,u.id]}, {:prompt=>"Select Manager"} %>
	    </div>        
	    <div>
		    <%=f.label :Description %>
		    <%=f.text_area :description,:rows=> 5  %>
      </div>
        
	    <div class="input-append date" id="datepicker_est_start_date"  data-date="<%=Date.today.strftime('%d-%m-%Y')%>">
		    <%=f.label :Est_start_date %>	
        <input id = "project_est_start_date" name ="project[est_start_date]" readonly = "readonly" type = "text" value /> 		
    		<span class="add-on"><i class="icon-th"></i></span>
	    </div>

	    <div class="input-append date" id="datepicker_est_end_date" data-date="<%=Date.today.strftime('%d-%m-%Y')%>">
		    <%=f.label :Est_end_date %>		
    		<input id = "project_est_end_date" name ="project[est_end_date]" readonly = "readonly" type = "text" value />
    		<span class="add-on"><i class="icon-th"></i></span>
	    </div><br>

     
    	<div>
		    <%=f.label :Additional_details %>
	    	<%=f.text_area :additional_details,:rows=> 5%>
	    </div>
    	<div>
		    <%= f.submit "Submit" , class: "btn" %>
		    <%= link_to "Cancel", projects_path, class:"btn" %>
	    </div>
    <% end %>

app/views/projects/edit.html.erb
<%= render 'form' %>

app/views/projects/index.html.erb
<h2>Projects</h2>
<div style="clear:both;"></div>               
<table class = table "table-bordered"   cellspacing="0" cellpadding="0" border="0" style="overflow-x:auto;">
	<tr class="rowH" height="30">
		<th>Project Name</th>
    <th>Manager</th>
    <th>Description</th>
		<th>Est. start date</th>
		<th>Est. end date</th>
    <th>Additional Details</th>
		<th>Actions</th>  
	</tr>
	  <% @projects.each do |p| %>
	  <tr class = '<%= cycle("rowB", "rowA") %>' >
		  <td><%=p.project_name%></td>
		  <td><%=p.user.email.present? ? p.user.email : "" %></td>
		  <td><%=p.description%></td>	
		
		  <td><%=p.est_start_date%></td>
		  <td><%=p.est_end_date%></td>
		  <td><%=p.additional_details%></td>
	
		  <td>
			  <li class="dropdown" style="list-style:none;">
		      <%= link_to "Click Here" , "#",  :'data-toggle' => "dropdown", class: "dropdown-toggle"  %>
				   <ul class="dropdown-menu" style="list-style:none;">
					   <li><%= link_to 'Edit', edit_project_path(p)%></li>
					   <li><%= link_to 'Delete', project_path(p), :method=> :delete %></li>
   					 <li><%= link_to 'Show', project_path(p) %></li>
             <li><%= link_to "View Repository", project_project_repositories_path(p) %></li>
             <li><%=link_to "View Team ", project_project_users_path(p) %></li>
	           <li><%=link_to "View Modules", project_project_modules_path(p) %></li>
	           <li><%= link_to "Login credentials", project_login_details_path(p) %></li>
           </ul>
			  </li>
		  </td>
	</tr>
	<% end %>
</table>
<div class="pull-right">
		<%= link_to "Add New Project", new_project_path, class: "btn"  %>
</div> 

app/views/projects/new.html.erb
<h1>New Project</h1>
<%= render 'form' %>

app/views/projects/show.html.erb
<table class = table "table-bordered"   cellspacing="0" cellpadding="0" >
 
	
	
	<tr>
		<td><b>Project Name</b></td>
		<td><%=@project.project_name%></td>
	</tr>
        <tr>
		<td><b>Manager</b></td>
		<td><%=@project.user.email%></td>
	</tr
	<tr>
		<td><b>Description</b></td>
		<td><%=@project.description%></td>
	</tr>
        
  <tr>
		<td><b>Est start date</b></td>
		<td><%=@project.est_start_date%></td>
	</tr>
  <tr>
		<td><b>Est end date</b></td>
		<td><%=@project.est_end_date%></td>
	</tr>
	
  <tr>
		<td><b>Additional Details</b></font></td>
		<td><%=@project.additional_details%></td>
	</tr>
	
	
	
 </table border>
           
               
	    